# Generated by Django 4.1 on 2022-08-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intId', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('qrCodeId', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('oldLocations', models.CharField(max_length=1000)),
            ],
        ),
    ]
