# Generated by Django 4.1 on 2022-08-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='intId',
        ),
    ]
